// <auto-generated />
using System;
using FinViet.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinViet.Infrastructure.Migrations
{
    [DbContext(typeof(FinVietDbContext))]
    [Migration("20260603201718_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinViet.Domain.Entities.Admin", b =>
                {
                    b.Property<Guid>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("AdminId")
                        .HasName("admin_pkey");

                    b.HasIndex(new[] { "Email" }, "admin_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "admin_username_key")
                        .IsUnique();

                    b.ToTable("admin", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.AiReport", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("report_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("GeneratedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("SpendingScore")
                        .HasColumnType("integer")
                        .HasColumnName("spending_score");

                    b.HasKey("ReportId")
                        .HasName("ai_report_pkey");

                    b.HasIndex("CustomerId");

                    b.ToTable("ai_report", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.AiReportDetail", b =>
                {
                    b.Property<Guid>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("detail_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CriterionId")
                        .HasColumnType("uuid")
                        .HasColumnName("criterion_id");

                    b.Property<Guid?>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("DetailId")
                        .HasName("ai_report_detail_pkey");

                    b.HasIndex("CriterionId");

                    b.HasIndex("ReportId");

                    b.ToTable("ai_report_detail", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.BudgetPlan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plan_name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("PlanId")
                        .HasName("budget_plan_pkey");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ModelId");

                    b.ToTable("budget_plan", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("category_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_name");

                    b.Property<string>("ExpenseClass")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("expense_class");

                    b.Property<bool?>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_mandatory");

                    b.Property<string>("ModelBucket")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_bucket");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("CategoryId")
                        .HasName("category_pkey");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.CategoryBudget", b =>
                {
                    b.Property<Guid>("CategoryBudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("category_budget_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("AmountLimit")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amount_limit");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<decimal?>("CurrentSpent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("current_spent")
                        .HasDefaultValueSql("0.00");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<decimal?>("ThresholdPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("threshold_pct");

                    b.Property<string>("ThresholdType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("threshold_type");

                    b.HasKey("CategoryBudgetId")
                        .HasName("category_budget_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PlanId");

                    b.ToTable("category_budget", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.CategoryCorrectionLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<Guid?>("CorrectedCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("corrected_category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("OriginalAiGuess")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("original_ai_guess");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("LogId")
                        .HasName("category_correction_log_pkey");

                    b.HasIndex("AdminId");

                    b.HasIndex("CorrectedCategoryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TransactionId");

                    b.ToTable("category_correction_log", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid?>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sender_type");

                    b.Property<DateTime?>("Timestamps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamps")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("MessageId")
                        .HasName("chat_message_pkey");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReportId");

                    b.ToTable("chat_message", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'ACTIVE'::character varying");

                    b.HasKey("CustomerId")
                        .HasName("customer_pkey");

                    b.HasIndex("AdminId");

                    b.HasIndex(new[] { "Email" }, "customer_email_key")
                        .IsUnique();

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.CustomerSubscription", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'ACTIVE'::character varying");

                    b.HasKey("SubscriptionId")
                        .HasName("customer_subscription_pkey");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PlanId");

                    b.ToTable("customer_subscription", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.FinancialModel", b =>
                {
                    b.Property<Guid>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("model_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AllocationRules")
                        .HasColumnType("jsonb")
                        .HasColumnName("allocation_rules");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_type");

                    b.HasKey("ModelId")
                        .HasName("financial_model_pkey");

                    b.ToTable("financial_model", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.ImportBatch", b =>
                {
                    b.Property<Guid>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<DateTime?>("ImportDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("import_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("BatchId")
                        .HasName("import_batch_pkey");

                    b.HasIndex("CustomerId");

                    b.HasIndex("WalletId");

                    b.ToTable("import_batch", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.IncomeSource", b =>
                {
                    b.Property<Guid>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("source_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("SourceId")
                        .HasName("income_source_pkey");

                    b.HasIndex("CustomerId");

                    b.ToTable("income_source", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.ModelAllocation", b =>
                {
                    b.Property<Guid>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("allocation_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_type");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percentage");

                    b.HasKey("AllocationId")
                        .HasName("model_allocation_pkey");

                    b.HasIndex("ModelId");

                    b.ToTable("model_allocation", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CategoryBudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_budget_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("NotificationId")
                        .HasName("notification_pkey");

                    b.HasIndex("CategoryBudgetId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("GoalId");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.SavingGoal", b =>
                {
                    b.Property<Guid>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("CurrentAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("current_amount")
                        .HasDefaultValueSql("0.00");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("goal_name");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("target_amount");

                    b.HasKey("GoalId")
                        .HasName("saving_goal_pkey");

                    b.HasIndex("CustomerId");

                    b.ToTable("saving_goal", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.SavingGoalContribution", b =>
                {
                    b.Property<Guid>("ContributionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("contribution_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ContributionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contribution_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.HasKey("ContributionId")
                        .HasName("saving_goal_contribution_pkey");

                    b.HasIndex("GoalId");

                    b.ToTable("saving_goal_contribution", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.ScoringCriterion", b =>
                {
                    b.Property<Guid>("CriterionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("criterion_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CriterionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criterion_name");

                    b.Property<string>("Formula")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("formula");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight");

                    b.HasKey("CriterionId")
                        .HasName("scoring_criteria_pkey");

                    b.ToTable("scoring_criteria", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("FeaturesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("features_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.HasKey("PlanId")
                        .HasName("subscription_plan_pkey");

                    b.ToTable("subscription_plan", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.SystemAnalytic", b =>
                {
                    b.Property<Guid>("AnalyticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("analytics_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("metric_name");

                    b.Property<decimal>("MetricValue")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("metric_value");

                    b.Property<DateTime?>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("AnalyticsId")
                        .HasName("system_analytics_pkey");

                    b.HasIndex("AdminId");

                    b.ToTable("system_analytics", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid?>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<DateTime?>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transaction_type");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("TransactionId")
                        .HasName("transaction_pkey");

                    b.HasIndex("BatchId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ReportId");

                    b.HasIndex("SourceId");

                    b.HasIndex("WalletId");

                    b.ToTable("transaction", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("balance")
                        .HasDefaultValueSql("0.00");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("WalletName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("wallet_name");

                    b.Property<string>("WalletType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("wallet_type");

                    b.HasKey("WalletId")
                        .HasName("wallet_pkey");

                    b.HasIndex("CustomerId");

                    b.ToTable("wallet", (string)null);
                });

            modelBuilder.Entity("FinViet.Domain.Entities.AiReport", b =>
                {
                    b.HasOne("FinViet.Domain.Entities.Customer", "Customer")
                        .WithMany("AiReports")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("ai_report_customer_id_fkey");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.AiReportDetail", b =>
                {
                    b.HasOne("FinViet.Domain.Entities.ScoringCriterion", "Criterion")
                        .WithMany("AiReportDetails")
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("ai_report_detail_criterion_id_fkey");

                    b.HasOne("FinViet.Domain.Entities.AiReport", "Report")
                        .WithMany("AiReportDetails")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("ai_report_detail_report_id_fkey");

                    b.Navigation("Criterion");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.BudgetPlan", b =>
                {
                    b.HasOne("FinViet.Domain.Entities.Customer", "Customer")
                        .WithMany("BudgetPlans")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("budget_plan_customer_id_fkey");

                    b.HasOne("FinViet.Domain.Entities.FinancialModel", "Model")
                        .WithMany("BudgetPlans")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("budget_plan_model_id_fkey");

                    b.Navigation("Customer");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.CategoryBudget", b =>
                {
                    b.HasOne("FinViet.Domain.Entities.Category", "Category")
                        .WithMany("CategoryBudgets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("category_budget_category_id_fkey");

                    b.HasOne("FinViet.Domain.Entities.BudgetPlan", "Plan")
                        .WithMany("CategoryBudgets")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("category_budget_plan_id_fkey");

                    b.Navigation("Category");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.CategoryCorrectionLog", b =>
                {
                    b.HasOne("FinViet.Domain.Entities.Admin", "Admin")
                        .WithMany("CategoryCorrectionLogs")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("category_correction_log_admin_id_fkey");

                    b.HasOne("FinViet.Domain.Entities.Category", "CorrectedCategory")
                        .WithMany("CategoryCorrectionLogs")
                        .HasForeignKey("CorrectedCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("category_correction_log_corrected_category_id_fkey");

                    b.HasOne("FinViet.Domain.Entities.Customer", "Customer")
                        .WithMany("CategoryCorrectionLogs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("category_correction_log_customer_id_fkey");

                    b.HasOne("FinViet.Domain.Entities.Transaction", "Transaction")
                        .WithMany("CategoryCorrectionLogs")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("category_correction_log_transaction_id_fkey");

                    b.Navigation("Admin");

                    b.Navigation("CorrectedCategory");

                    b.Navigation("Customer");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("FinViet.Domain.Entities.Customer", "Customer")
                        .WithMany("ChatMessages")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("chat_message_customer_id_fkey");

                    b.HasOne("FinViet.Domain.Entities.AiReport", "Report")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("chat_message_report_id_fkey");

                    b.Navigation("Customer");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.Customer", b =>
                {
                    b.HasOne("FinViet.Domain.Entities.Admin", "Admin")
                        .WithMany("Customers")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("customer_admin_id_fkey");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.CustomerSubscription", b =>
                {
                    b.HasOne("FinViet.Domain.Entities.Customer", "Customer")
                        .WithMany("CustomerSubscriptions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("customer_subscription_customer_id_fkey");

                    b.HasOne("FinViet.Domain.Entities.SubscriptionPlan", "Plan")
                        .WithMany("CustomerSubscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("customer_subscription_plan_id_fkey");

                    b.Navigation("Customer");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.ImportBatch", b =>
                {
                    b.HasOne("FinViet.Domain.Entities.Customer", "Customer")
                        .WithMany("ImportBatches")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("import_batch_customer_id_fkey");

                    b.HasOne("FinViet.Domain.Entities.Wallet", "Wallet")
                        .WithMany("ImportBatches")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("import_batch_wallet_id_fkey");

                    b.Navigation("Customer");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.IncomeSource", b =>
                {
                    b.HasOne("FinViet.Domain.Entities.Customer", "Customer")
                        .WithMany("IncomeSources")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("income_source_customer_id_fkey");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.ModelAllocation", b =>
                {
                    b.HasOne("FinViet.Domain.Entities.FinancialModel", "Model")
                        .WithMany("ModelAllocations")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("model_allocation_model_id_fkey");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.Notification", b =>
                {
                    b.HasOne("FinViet.Domain.Entities.CategoryBudget", "CategoryBudget")
                        .WithMany("Notifications")
                        .HasForeignKey("CategoryBudgetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("notification_category_budget_id_fkey");

                    b.HasOne("FinViet.Domain.Entities.Customer", "Customer")
                        .WithMany("Notifications")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("notification_customer_id_fkey");

                    b.HasOne("FinViet.Domain.Entities.SavingGoal", "Goal")
                        .WithMany("Notifications")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("notification_goal_id_fkey");

                    b.Navigation("CategoryBudget");

                    b.Navigation("Customer");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.SavingGoal", b =>
                {
                    b.HasOne("FinViet.Domain.Entities.Customer", "Customer")
                        .WithMany("SavingGoals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("saving_goal_customer_id_fkey");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.SavingGoalContribution", b =>
                {
                    b.HasOne("FinViet.Domain.Entities.SavingGoal", "Goal")
                        .WithMany("SavingGoalContributions")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("saving_goal_contribution_goal_id_fkey");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.SystemAnalytic", b =>
                {
                    b.HasOne("FinViet.Domain.Entities.Admin", "Admin")
                        .WithMany("SystemAnalytics")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("system_analytics_admin_id_fkey");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("FinViet.Domain.Entities.ImportBatch", "Batch")
                        .WithMany("Transactions")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transaction_batch_id_fkey");

                    b.HasOne("FinViet.Domain.Entities.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transaction_category_id_fkey");

                    b.HasOne("FinViet.Domain.Entities.AiReport", "Report")
                        .WithMany("Transactions")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transaction_report_id_fkey");

                    b.HasOne("FinViet.Domain.Entities.IncomeSource", "Source")
                        .WithMany("Transactions")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transaction_source_id_fkey");

                    b.HasOne("FinViet.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("transaction_wallet_id_fkey");

                    b.Navigation("Batch");

                    b.Navigation("Category");

                    b.Navigation("Report");

                    b.Navigation("Source");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("FinViet.Domain.Entities.Customer", "Customer")
                        .WithMany("Wallets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("wallet_customer_id_fkey");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.Admin", b =>
                {
                    b.Navigation("CategoryCorrectionLogs");

                    b.Navigation("Customers");

                    b.Navigation("SystemAnalytics");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.AiReport", b =>
                {
                    b.Navigation("AiReportDetails");

                    b.Navigation("ChatMessages");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.BudgetPlan", b =>
                {
                    b.Navigation("CategoryBudgets");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.Category", b =>
                {
                    b.Navigation("CategoryBudgets");

                    b.Navigation("CategoryCorrectionLogs");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.CategoryBudget", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.Customer", b =>
                {
                    b.Navigation("AiReports");

                    b.Navigation("BudgetPlans");

                    b.Navigation("CategoryCorrectionLogs");

                    b.Navigation("ChatMessages");

                    b.Navigation("CustomerSubscriptions");

                    b.Navigation("ImportBatches");

                    b.Navigation("IncomeSources");

                    b.Navigation("Notifications");

                    b.Navigation("SavingGoals");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.FinancialModel", b =>
                {
                    b.Navigation("BudgetPlans");

                    b.Navigation("ModelAllocations");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.ImportBatch", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.IncomeSource", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.SavingGoal", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("SavingGoalContributions");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.ScoringCriterion", b =>
                {
                    b.Navigation("AiReportDetails");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("CustomerSubscriptions");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("CategoryCorrectionLogs");
                });

            modelBuilder.Entity("FinViet.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("ImportBatches");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}

